export const TYPES = {
  SET_USERINFO: "SET_USERINFO",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTE_SUCCESS: "REGISTER_SUCCESS",
  REGISTE_FAIL: "REGISTER_FAIL",
  // Token
  SET_ACCESSTOKEN: "SET_ACCESSTOKEN",
  SET_REFRESHTOKEN: "SETREFRESHTOKEN",
  // Modal
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  // Modal Type
  MODAL_TYPES: "MODAL_TYPES",

  LOGOUT: "LOGOUT",
  GET_ERROR: "GET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
};

export const TIC_TYPE = {
  SET_X_WIN: "SET_X_WIN",
  SET_O_WIN: "SET_O_WIN",
  SET_DRAW: "SET_DRAW",
  MAKE_MOVE: "MAKE_MOVE",
  CREATE_NEW_GAME: "CREATE_NEW_GAME",
  RESET_GAME_STATE: "RESET_GAME_STATE",
  SET_WHO_MOVE_FIRST: "SET_WHO_MOVE_FIRST",
  SET_GAME_MODE: "SET_GAME_MODE",
  SET_AI_TURN: "SET_AI_TURN",
};

