export const TYPES = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGOUT: "LOGOUT",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_PROFILE: "UPDATE_PROFILE_PICTURE",
};
