export const TYPES = {
  SET_USERINFO: "SET_USERINFO",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTE_SUCCESS: "REGISTER_SUCCESS",
  REGISTE_FAIL: "REGISTER_FAIL",
  // Token
  SET_ACCESSTOKEN: "SET_ACCESSTOKEN",
  SET_REFRESHTOKEN: "SETREFRESHTOKEN",
  // Modal
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  // Modal Type
  MODAL_TYPES: "MODAL_TYPES",

  LOGOUT: "LOGOUT",
  GET_ERROR: "GET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
};
